title = "Koormappen"
baseURL = "https://orthodox-ronl.github.io/koor/"
# baseURL = "http://localhost:1313/"
defaultContentLanguage = "nl"
languageCode = "nl-NL"
enableGitInfo = true
relativeURLs = false
canonifyURLs = false

[params]
footerText = "(C) YEAR orthodox-ronl.github.com. "
headerText = "Orthodoxe Koormappen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

