title = "Koormappen"
baseURL = "https://orthodox-groningen.github.io/koor/preview/"
# baseURL = "http://localhost:1313/koor/"
defaultContentLanguage = "nl"
languageCode = "nl-NL"
enableGitInfo = true
relativeURLs = false
canonifyURLs = false

[params]
footerText = "(C) YEAR RO Parochie Groningen. "
headerText = "Koormappen Groningen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
